# run_dqd_batch.R
# ---------------------------------------------------------------------------
# Batch variant of run_dqd.R for the system-evaluation harness.
#
#   Rscript R/run_dqd_batch.R          (or  source("R/run_dqd_batch.R")  in RStudio)
#
# Iterates over every per-source OMOP export produced by eval/run_eval.py
# (dqd/eval/omop/<key>/omop_cdm.json) plus the merged dqd/eval/omop/combined/,
# builds a fresh SQLite CDM for each via build_cdm_sqlite() (reused verbatim from
# load_cdm.R), runs the DataQualityDashboard batch, and writes per-source
# results.json + results.csv + summary.txt under dqd/eval/dqd_results/<key>/.
# The original single-input run_dqd.R is untouched.
#
# The lean Athena vocabulary in dqd/vocab/ (CONCEPT + small lookup tables) is
# loaded => CONCEPT-level checks run and isForeignKey checks on *_concept_id
# columns resolve against the real CONCEPT table (TABLE+FIELD+CONCEPT). If the
# vocab/ folder is absent, build_cdm_sqlite falls back to TABLE+FIELD only.
# ---------------------------------------------------------------------------

suppressPackageStartupMessages({
  library(here)
})

# Repair JAVA_HOME for rJava BEFORE DatabaseConnector loads it.
source(file.path(here::here(), "R", "java_setup.R"))

suppressPackageStartupMessages({
  library(DatabaseConnector)
  library(DataQualityDashboard)
})

ROOT       <- here::here()
EVAL_DIR   <- file.path(ROOT, "eval")
OMOP_DIR   <- file.path(EVAL_DIR, "omop")
RESULTS_DIR <- file.path(EVAL_DIR, "dqd_results")

source(file.path(ROOT, "R", "load_cdm.R"))

dir.create(RESULTS_DIR, recursive = TRUE, showWarnings = FALSE)

# ── discover datasets ────────────────────────────────────────────────────────
# Every subdirectory of eval/omop/ that contains an omop_cdm.json. "combined" is
# run last so it appears at the bottom of the console log.
all_dirs <- list.dirs(OMOP_DIR, recursive = FALSE, full.names = FALSE)
has_export <- function(k) file.exists(file.path(OMOP_DIR, k, "omop_cdm.json"))
keys <- all_dirs[vapply(all_dirs, has_export, logical(1))]
keys <- c(setdiff(keys, "combined"), intersect(keys, "combined"))

if (length(keys) == 0) {
  stop("No omop_cdm.json exports found under ", OMOP_DIR,
       " — run `python eval/run_eval.py finalize` and `combine` first.", call. = FALSE)
}
message("Datasets to evaluate: ", paste(keys, collapse = ", "))

# ── summary writer (adapted from run_dqd.R::print_summary; writes to a file) ──
write_summary <- function(results, key, out_path) {
  df <- results$CheckResults
  con <- file(out_path, open = "wt")
  on.exit(close(con), add = TRUE)
  w <- function(...) cat(..., "\n", sep = "", file = con)

  w("==================== DQD SUMMARY: ", key, " ====================")
  if (is.null(df) || nrow(df) == 0) {
    w("No check results returned.")
    return(invisible(NULL))
  }
  status <- ifelse(df$isError == 1, "ERROR",
                   ifelse(df$notApplicable == 1, "NOT_APPLICABLE",
                          ifelse(df$failed == 1, "FAIL", "PASS")))
  w("Total checks executed: ", nrow(df))
  w("")
  w("By status:")
  st <- as.data.frame(table(status), stringsAsFactors = FALSE)
  for (i in seq_len(nrow(st))) w("  ", st$status[i], ": ", st$Freq[i])

  if ("category" %in% names(df)) {
    w("")
    w("By Kahn category x status:")
    ct <- table(df$category, status)
    cats <- rownames(ct); cols <- colnames(ct)
    w("  ", paste(sprintf("%-16s", c("category", cols)), collapse = ""))
    for (cat in cats) {
      w("  ", sprintf("%-16s", cat),
        paste(sprintf("%-16s", as.character(ct[cat, ])), collapse = ""))
    }
  }

  fails <- df[status == "FAIL", , drop = FALSE]
  if (nrow(fails) > 0) {
    w("")
    w("Failing checks (", nrow(fails), "):")
    cols <- intersect(c("checkName", "cdmTableName", "cdmFieldName",
                        "pctViolatedRows", "thresholdValue"), names(fails))
    show <- fails[order(-fails$pctViolatedRows), cols, drop = FALSE]
    show <- utils::head(show, 60)
    w("  ", paste(sprintf("%-26s", cols), collapse = ""))
    for (i in seq_len(nrow(show))) {
      w("  ", paste(sprintf("%-26s", as.character(unlist(show[i, ]))), collapse = ""))
    }
  }
  w("")
  w("(generated by run_dqd_batch.R; check levels per vocabulary presence — ",
    "TABLE+FIELD+CONCEPT when the Athena CONCEPT vocabulary is loaded)")
}

# ── run DQD per dataset ──────────────────────────────────────────────────────
overall <- list()
for (key in keys) {
  message("\n=====================================================")
  message("Evaluating: ", key)
  message("=====================================================")

  input_dir <- file.path(OMOP_DIR, key)
  out_dir   <- file.path(RESULTS_DIR, key)
  dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
  db_path   <- file.path(out_dir, "cdm.sqlite")

  built <- build_cdm_sqlite(input_dir = input_dir, db_path = db_path,
                            vocab_dir = file.path(ROOT, "vocab"))

  check_levels <- if (built$vocab_loaded) c("TABLE", "FIELD", "CONCEPT") else c("TABLE", "FIELD")

  results <- tryCatch(
    DataQualityDashboard::executeDqChecks(
      connectionDetails     = built$connectionDetails,
      cdmDatabaseSchema     = "main",
      resultsDatabaseSchema = "main",
      vocabDatabaseSchema   = "main",
      cdmSourceName         = paste0("Harmonia - ", key),
      cdmVersion            = "5.4",
      checkLevels           = check_levels,
      outputFolder          = out_dir,
      outputFile            = "results.json",
      writeToTable          = FALSE,
      writeToCsv            = FALSE,
      verboseMode           = FALSE
    ),
    error = function(e) {
      message("  !! executeDqChecks failed for ", key, ": ", conditionMessage(e))
      NULL
    }
  )

  if (is.null(results)) next

  utils::write.csv(results$CheckResults, file.path(out_dir, "results.csv"),
                   row.names = FALSE)
  write_summary(results, key, file.path(out_dir, "summary.txt"))

  df <- results$CheckResults
  status <- ifelse(df$isError == 1, "ERROR",
                   ifelse(df$notApplicable == 1, "NOT_APPLICABLE",
                          ifelse(df$failed == 1, "FAIL", "PASS")))
  overall[[key]] <- c(
    total = nrow(df),
    PASS = sum(status == "PASS"),
    FAIL = sum(status == "FAIL"),
    NA_ = sum(status == "NOT_APPLICABLE"),
    ERROR = sum(status == "ERROR")
  )
  message(sprintf("  %s: %d checks  PASS=%d FAIL=%d NA=%d ERROR=%d",
                  key, overall[[key]]["total"], overall[[key]]["PASS"],
                  overall[[key]]["FAIL"], overall[[key]]["NA_"], overall[[key]]["ERROR"]))
}

# ── overall index ────────────────────────────────────────────────────────────
if (length(overall) > 0) {
  idx <- do.call(rbind, lapply(names(overall), function(k) {
    data.frame(dataset = k, t(overall[[k]]), check.names = FALSE)
  }))
  utils::write.csv(idx, file.path(RESULTS_DIR, "overview.csv"), row.names = FALSE)
  message("\n==================== OVERALL ====================")
  print(idx, row.names = FALSE)
  message("Per-dataset results under: ", RESULTS_DIR)
  message("Overview written to:       ", file.path(RESULTS_DIR, "overview.csv"))
}
